name: 'Setup NetCode Patcher'
description: 'Sets up NetCode Patcher for patching Unity mods that depend on NetCode for GameObjects.'
author: 'Lordfirespeed'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'hard-drive'
  color: 'purple'

# Define your inputs here.
inputs:
  netcode-patcher-version:
    description: 'NetCode patcher version to setup'
    required: true
  deps-packages:
    description: 'JSON array of NuGet package IDs and versions to copy reference assemblies from.'
    default: "[]"
  deps-paths:
    description: 'JSON array of reference assembly string paths to copy from.'
    default: "[]"
  target-framework:
    description: 'Target framework moniker used to resolve dependency assemblies.'
    required: true

outputs:
  netcode-patcher-directory:
    description: 'Netcode Patcher installation directory'

runs:
  using: node20
  main: dist/index.js
