name: 'Setup NetCode Weaver'
description: 'Sets up NetCode Weaver for patching Unity mods that depend on NetCode for GameObjects.'
author: 'Lordfirespeed'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'hard-drive'
  color: 'purple'

# Define your inputs here.
inputs:
  netcode-weaver-version:
    description: 'NetCode weaver version to setup'
    required: true
  deps-packages:
    description: 'JSON array of NuGet package IDs and versions to copy reference assemblies from.'
    default: "[]"
  target-framework:
    description: 'Target framework moniker used to resolve dependency assemblies.'
    required: true

outputs:
  netcode-weaver-directory:
    description: 'Netcode Weaver installation directory'

runs:
  using: node20
  main: dist/index.js
